# Generated by Django 5.0.6 on 2024-06-13 04:28

import caropa_app.models.home
import caropa_app.models.product
import django.db.models.deletion
import django_attachments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[caropa_app.models.home.validate_title])),
                ('image', models.ImageField(upload_to='home/categories/')),
            ],
            options={
                'verbose_name': 'Home Category',
                'verbose_name_plural': 'Home Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_3_title', models.CharField(max_length=100)),
                ('section_3_description', models.TextField()),
                ('section_5_title', models.CharField(max_length=100)),
                ('section_5_description', models.TextField()),
                ('section_5_image', models.ImageField(upload_to='home/images/')),
                ('carousel_presentation', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, related_name='homes_with_carousel', to='django_attachments.library')),
                ('section_3_gallery', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, related_name='homes_with_section_3_gallery', to='django_attachments.library')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, validators=[caropa_app.models.product.validate_ref])),
                ('trending_now', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='products', to='caropa_app.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='caropa_app.color')),
                ('gallery', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, related_name='products_with_attachment', to='django_attachments.library')),
                ('home_categories', models.ManyToManyField(related_name='products', to='caropa_app.homecategory')),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='caropa_app.productdetail')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='caropa_app.size')),
            ],
        ),
    ]
