# Generated by Django 5.0.6 on 2024-06-10 20:50

import caropa_app.models.home
import django.db.models.deletion
import django_attachments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caropa_app', '0001_initial'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[caropa_app.models.home.validate_title])),
                ('content', models.TextField()),
                ('gallery', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, related_name='homes_with_attachment', to='django_attachments.library')),
            ],
        ),
    ]
