# Generated by Django 5.0.6 on 2024-06-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caropa_app', '0002_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Homes'},
        ),
    ]
