# Generated by Django 5.0.6 on 2024-06-10 21:30

import caropa_app.models.home
import django.db.models.deletion
import django_attachments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caropa_app', '0003_alter_home_options'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='content',
            new_name='section_3_description',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='section_3_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='gallery',
        ),
        migrations.AddField(
            model_name='home',
            name='carousel_presentation',
            field=django_attachments.fields.GalleryField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homes_with_carousel', to='django_attachments.library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='section_3_gallery',
            field=django_attachments.fields.GalleryField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homes_with_section_3_gallery', to='django_attachments.library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='banners',
            field=models.ManyToManyField(related_name='home_banners', to='caropa_app.banner'),
        ),
        migrations.CreateModel(
            name='HomeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[caropa_app.models.home.validate_title])),
                ('image', models.ImageField(upload_to='Home/categories/')),
                ('products', models.ManyToManyField(related_name='home_categories', to='caropa_app.product')),
            ],
            options={
                'verbose_name': 'Home Category',
                'verbose_name_plural': 'Home Categories',
            },
        ),
    ]
