# Generated by Django 5.0.6 on 2024-06-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caropa_app', '0004_banner_rename_content_home_section_3_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='banners',
        ),
    ]
