# Generated by Django 5.0.6 on 2024-06-11 22:17

import caropa_app.models.home
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caropa_app', '0005_remove_home_banners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecategories',
            name='products',
        ),
        migrations.AddField(
            model_name='category',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='section_5_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='section_5_image',
            field=models.ImageField(default=1, upload_to='Home/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='section_5_title',
            field=models.CharField(default=1, max_length=100, validators=[caropa_app.models.home.validate_title]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categories_home',
            field=models.ManyToManyField(related_name='Home_Categories', to='caropa_app.homecategories'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_now',
            field=models.BooleanField(default=False),
        ),
    ]
